version: "3"
services: 
    mysql:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: studinfosystem

        ports:
            - "3306:3306"
      
    myphp:
        build: .
        ports:
            - "80:80"

    myadmin:
        image: phpmyadmin/phpmyadmin
        ports: 
            - "8080:80"
        environment: 
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
        restart: always
        depends_on: 
            - mysql